### ISSUE TITLE
Duplicate Publishing migrations file

### ISSUE THREAD

**Issue by tangqi198707** [spatie/laravel-tags#146]
Duplicate Publishing migrations file

Has anyone ever encountered such a problem?

How to fix it

**Comment by freekmurze** [comment]
Can't reproduce this.

**Comment by noxify** [comment]
Hi,

i was able to reproduce it.

Environment:
* Homestead
* Laravel 5.7.14
* Spatie Tags 2.1.4

STR:
1. Open the Terminal
2. type `php artisan vendor:publish`
3. Choose the tags package or choose to publish everything

The migration file will be generated again.

My opinion: This is a expected behavior, because the migration will be generated from a stub.

@tangqi198707 - Workaround: don't publish all vendors ;)  or delete the duplicates.
