### ISSUE TITLE
Retrieve all models having a tag?

### ISSUE THREAD

**Issue by FaridAghili** [spatie/laravel-tags#163]
Is it possible?

```php
// Get collection of all modules having this $tag
$models = $tag->models();
```
Or
```php
$models = Tag::models('tag-name', 'tag-type');
```

**Comment by freekmurze** [comment]
This currently isn't possbile. The relation between models and tags is a `MorphToMany` one.

To get the inverse you should use [a custom model](https://docs.spatie.be/laravel-tags/v2/advanced-usage/using-your-own-tag-model) and add your own reverse relations on it ([a `morphedByMany` one](https://laravel.com/docs/5.7/eloquent-relationships#polymorphic-relationships)).

**Comment by guoxiangke** [comment]
Works for me:
$models = MyModel::withAnyTags(['tag2'])->get();
$models = MyModel::withAnyTags(['tag1'], 'ly')->get();

**Comment by m0stwan1ed** [comment]
In case of looking for the answer by someone else I'll leave this information here.

Instead of replacing `Tag` model with a written from scratch one I've extended it with necessary for my relations.

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Spatie\Tags\Tag as BaseTag;

class Tag extends BaseTag
{
    public function posts(): MorphToMany
    {
        return $this->morphedByMany(Post::class, 'taggable');
    }
}
```

I did that in this way because I think in future it prevent problems caused by updating of `Spatie\Tags\Tag` model in package affected by any of breaking changes (changing of model or adding new functionality).

And of course for consistency maintenance we also can override `getTagClassName()` function.
