### ISSUE TITLE
How to enforce consistency with multi-language tags 

### ISSUE THREAD

**Issue by Robertbaelde** [spatie/laravel-tags#201]
We currently rely on the package for toggling some features on-of for certain models. This works great. But we're moving to multi-lingual now, causing the issue that tags are only defined in 1 locale. Would love to create a PR to improve the package here, but I'm wondering what the right approach might be. 

- We could add a key column to the table. Passing a key by creating (or getting it from the name passed as default), and be able to use this key for methods like withAllTags or withAnyTags would solve the issue. 

- We could make the locale getter configurable in the package. By doing this we could enforce one locale being used as a key for example. 

- Other ideas?

**Comment by Robertbaelde** [comment]
Hi @freekmurze ,
Tnx for the quick answer. (Seems like the docs are offline, 502 Bad gateway). 
Maybe i was unclear in the original issue. What i mean is, that it gets tricky with translations. 

Let me show an example: 
```
    App::setLocale('NL');
    $model = \App\Model::first();
    $model->attachTag("Foo");

    \App\Model::withAllTags('Foo')->count(); // Results in 1, as expected 
    
    App::setLocale('EN');

    \App\Model::withAllTags('Foo')->count(); // Results in 0

```
So having a default language fallback, or maybe a key, might improve the usage of tags for things like turning of/on specific features for models. Or doing analyses based on specific tags added.

Might be that we're the only one using the package in this way. If thats the case, maybe a fork is better. Otherwise I'd like to add something to solve this.

**Comment by freekmurze** [comment]
If the modifications needed are simple and well tested, I'd be open to add it to the package.

In the other case, feel free to fork our code.

**Comment by robclancy** [comment]
The way translations work kind of makes this package not work well with dynamic content, like adding tags to a blog post. Because depending on the user who makes it will change if the tags have a `name` or are just empty strings.  

My workaround is simply going to be to stop add a `names` getter that outputs the actual `name` value and client side I will just use the locale version or the first found (I don't think there will ever be a situation where a tag will properly get translated while using them dynamically, instead there will just be 2 versions if an english and spanish user do it).

I could also potentially have some UI attached to an untranslated tag that is displayed, so admins can translate them, while normal users just see the fallback.

**Comment by robclancy** [comment]
Came back to this issue again running into bugs and forgot I even wrote anything. I no longer see how the translation feature is useful at all unless a lot of custom logic is added. Since it can now be disabled (in a lame way, but still works) I will just disable it now.
