### ISSUE TITLE
Error running migration on MariaDB 10.1.16

### ISSUE THREAD

**Issue by mlanser** [spatie/laravel-tags#22]
I'm running Laravel 5.3 on Valet on Mac OSX Sierra with MariaDB 10.1.16 and am encountering the following error when trying to run migration:

_"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `slug` json not null, `type` varchar(255) null, `order_column` in' at line 1"_

As far as I can tell from reading various posts and MariaDB docs, it seems (somehow) that MariaDB only supports JSON with "CONNECT" engine. My current work-around is to make the following changes:

**from**
```
$table->json('name');
$table->json('slug');
```

**to**
```
$table->text('name');
$table->text('slug');
```

Will this change have an adverse effect anywhere else in the package code?

TIA,
-martin.

**Comment by sebastiandedeyne** [comment]
Unfortunately this package isn't compatible with MariaDB since it uses MySQL's JSON query syntax.

Until the json type is implemented, this package won't work in MariaDB. (it's is a high priority in the project, so hopefully soon)

Syntax example: https://github.com/spatie/laravel-tags/blob/master/src/Tag.php#L59
