### ISSUE TITLE
Question: how to extend this package to make it work with the Spatie Activity Logger?

### ISSUE THREAD

**Issue by gchaumont** [spatie/laravel-tags#23]
Hi, 

I am wondering how I could make both your packages work together without modifying Vendor files.
For example, logging when a user creates a tag. 

What would be the best / cleanest approach to make these packages observe each other after pulling them in?

I would appreciate if you could give me some advice on this.

**Comment by sebastiandedeyne** [comment]
I can think of two possible approaches:

You could listen to model events, and log your activity from there. Quick example:

```php
// It doesn't really matter where this code is stored, as long as it's executed,
// e.g. in a ServiceProvider

\Spatie\Tags\Tag::created(function (Tag $tag) {
    activity()
        ->performedOn($tag)
        ->causedBy(auth()->user())
        ->log("Tag {$tag->name} was created");
});
```

Or you could create a custom Tag model that uses the `LogsActivity` trait:

```php
namespace App;

class Tag extends \Spatie\Tags\Tag
{
    use LogsActivity;

    protected static $logAttributes = ['name'];
}
```

Then follow the steps to use your own tag model instead of the one provided by this package: https://docs.spatie.be/laravel-tags/v1/advanced-usage/using-your-own-tag-model

**Comment by gchaumont** [comment]
Many thanks for your answer.
So in case I would use many packages I would have to extend each model and apply the traits?
Isn't there a way to "centralise" or "automate" this?

**Comment by mhardaniel123** [comment]
Hi sir,
How about attach/detach event?
