### ISSUE TITLE
Tag names are case sensitive

### ISSUE THREAD

**Issue by cdbeaton** [spatie/laravel-tags#341]
Tags named e.g. `example` and `Example` are treated as two separate tags with identical slugs. As a result, models tagged with `Example` are not retrieved with `Model::withAnyTags(['example'])` as a user may expect. This behaviour could either be changed, or an additional scope could be added to specify a case-insensitive tag search.

**Comment by leonidlezner** [comment]
Kind of an old issue, but important to me. I'm getting duplicate tags, because people are entering values like "Hello" and "hello". `findFromString` is doing the case sensitive search because of the json object.

"... uses utf8mb4 with the binary collation, which is case-sensitive;"

I suppose the function findFromString should work like `scopeContaining`:

`return $query->whereRaw('lower(' . $this->getQuery()->getGrammar()->wrap('name->' . $locale) . ') like ?', ['%' . mb_strtolower($name) . '%']);`

**Comment by leonidlezner** [comment]
Function `findFromString` could be rewritten like this:

```
    public static function findFromString(string $name, string $type = null, string $locale = null)
    {
        $locale = $locale ?? static::getLocale();

        return static::query()->whereRaw('lower(' . static::query()->getGrammar()->wrap('name->' . $locale) . ') = ?', [mb_strtolower($name)])->first();
    }
```

**Comment by gbrits** [comment]
@leonidlezner I may be missing something, but why not use the slug for the lookups instead?
```
return static::query()
            ->where("slug->{$locale}", str_replace(' ','-',$name))
            ->get();
```
