### ISSUE TITLE
Does the package provides tag normalization capabilities?

### ISSUE THREAD

**Issue by durancu** [spatie/laravel-tags#78]

**Comment by freekmurze** [comment]
I don't know what tag normalization abilities are.

**Comment by durancu** [comment]
I mean no matter if user enter "tag" or "Tag" or "tAg", service will normalize the word as "Tag" preventing duplicates with similar or same word and different capitalization.

**Comment by freekmurze** [comment]
No, you need to normalize the tags yourself.

**Comment by mpociot** [comment]
I know this is an old issue, but I stumbled upon this and adding normalization into the package is actually pretty easy. 

So if anyone else is looking for a solution, here's what I did:

1. Create your own `Tag` class that extends from `Spatie\Tags\Tag`

In this class override the `findFromString` method to look for the generated slug instead of the `name`:

```php
<?php

namespace App\Models;

class Tag extends \Spatie\Tags\Tag
{
    public static function findFromString(string $name, string $type = null, string $locale = null)
    {
        $locale = $locale ?? app()->getLocale();

        $slugger = config('tags.slugger');

        $slugger = $slugger ?: 'str_slug';

        $slug = call_user_func($slugger, $name);

        return static::query()
            ->where("slug->{$locale}", $slug)
            ->where('type', $type)
            ->first();
    }
}
```

Next, go into your model that has the `HasTags` trait and configure your new tag model:

```php
public static function getTagClassName(): string
{
    return YourCustomTag::class;
}
```

That's it. Now instead of trying to look up new Tags by it's name, it looks for the slug, which you can use to normalize the tags.
